import type { Alpine } from 'alpinejs';
import './modules/shared/chart';
import normalVariance from './modules/normal-variance';
import betaPosterior from './modules/beta-posterior';
import clt from './modules/clt';
import lln from './modules/lln';
import convolution from './modules/convolution';
import demoivreLaplace from './modules/demoivre-laplace';
import bivariateNormals from './modules/bivariate-normals';
import markov from './modules/markov';
import rv from './modules/rv';
import confidence from './modules/confidence';
import covariance from './modules/covariance';
import randomIncidence from './modules/random-incidence';
import poisson from './modules/poisson';

export default (Alpine: Alpine) => {
  normalVariance(Alpine);
  betaPosterior(Alpine);
  clt(Alpine);
  lln(Alpine);
  convolution(Alpine);
  demoivreLaplace(Alpine);
  bivariateNormals(Alpine);
  markov(Alpine);
  rv(Alpine);
  confidence(Alpine);
  covariance(Alpine);
  randomIncidence(Alpine);
  poisson(Alpine);
};
